export const nutritionDb = [
  // Fruits
  { id: 1, name: "Banana", category: "Fruits", calories: 89, protein: "1.1g", carbs: "22.8g", fats: "0.3g", healthRating: 9, recommendation: "Excellent source of potassium and quick energy." },
  { id: 2, name: "Apple", category: "Fruits", calories: 52, protein: "0.3g", carbs: "13.8g", fats: "0.2g", healthRating: 9, recommendation: "High in fiber and vitamin C. Good for daily snacks." },
  { id: 3, name: "Orange", category: "Fruits", calories: 47, protein: "0.9g", carbs: "11.8g", fats: "0.1g", healthRating: 9, recommendation: "Rich in vitamin C and hydration. Supports immune health." },
  { id: 4, name: "Mango", category: "Fruits", calories: 60, protein: "0.8g", carbs: "15g", fats: "0.3g", healthRating: 8, recommendation: "High in vitamins A and C, but relatively high in sugars." },
  { id: 5, name: "Papaya", category: "Fruits", calories: 43, protein: "0.5g", carbs: "11g", fats: "0.3g", healthRating: 9, recommendation: "Great for digestion due to papain enzyme. Low in calories." },
  { id: 6, name: "Watermelon", category: "Fruits", calories: 30, protein: "0.6g", carbs: "7.6g", fats: "0.2g", healthRating: 9, recommendation: "Extremely hydrating (92% water). Low calorie and refreshing." },
  { id: 7, name: "Strawberry", category: "Fruits", calories: 32, protein: "0.7g", carbs: "7.7g", fats: "0.3g", healthRating: 9, recommendation: "Low calorie, high antioxidant berry. Great for heart health." },
  { id: 8, name: "Grape", category: "Fruits", calories: 69, protein: "0.7g", carbs: "18.1g", fats: "0.2g", healthRating: 8, recommendation: "Good source of antioxidants like resveratrol. Eat in moderation." },
  { id: 9, name: "Pineapple", category: "Fruits", calories: 50, protein: "0.5g", carbs: "13.1g", fats: "0.1g", healthRating: 8, recommendation: "Contains bromelain, which helps reduce inflammation." },
  { id: 10, name: "Pomegranate", category: "Fruits", calories: 83, protein: "1.7g", carbs: "18.7g", fats: "1.2g", healthRating: 9, recommendation: "Packed with anti-inflammatory compounds and vitamin K." },
  { id: 11, name: "Guava", category: "Fruits", calories: 68, protein: "2.6g", carbs: "14.3g", fats: "1g", healthRating: 10, recommendation: "Superfood high in dietary fiber and vitamin C." },
  { id: 12, name: "Kiwi", category: "Fruits", calories: 61, protein: "1.1g", carbs: "14.7g", fats: "0.5g", healthRating: 9, recommendation: "Promotes sleep quality and digestion. High in vitamin C." },
  { id: 13, name: "Peach", category: "Fruits", calories: 39, protein: "0.9g", carbs: "9.5g", fats: "0.3g", healthRating: 8, recommendation: "Provides moderate vitamins A and C. Good for digestion." },
  { id: 14, name: "Pear", category: "Fruits", calories: 57, protein: "0.4g", carbs: "15.2g", fats: "0.1g", healthRating: 9, recommendation: "High in soluble fiber which aids cholesterol control." },
  { id: 15, name: "Plum", category: "Fruits", calories: 46, protein: "0.7g", carbs: "11.4g", fats: "0.3g", healthRating: 8, recommendation: "Contains active phytonutrients. Good for bone health." },
  { id: 16, name: "Cherry", category: "Fruits", calories: 50, protein: "1g", carbs: "12.2g", fats: "0.3g", healthRating: 9, recommendation: "Helps reduce muscle soreness and improves sleep patterns." },
  { id: 17, name: "Blueberry", category: "Fruits", calories: 57, protein: "0.7g", carbs: "14.5g", fats: "0.3g", healthRating: 10, recommendation: "A top antioxidant fruit. Excellent for brain and heart health." },
  { id: 18, name: "Fig", category: "Fruits", calories: 74, protein: "0.8g", carbs: "19.2g", fats: "0.3g", healthRating: 8, recommendation: "High in calcium and iron. Helps regulate blood pressure." },
  { id: 19, name: "Apricot", category: "Fruits", calories: 48, protein: "1.4g", carbs: "11.1g", fats: "0.4g", healthRating: 8, recommendation: "Rich in beta-carotene. Protects eye and skin health." },
  { id: 20, name: "Avocado", category: "Fruits", calories: 160, protein: "2g", carbs: "8.5g", fats: "14.7g", healthRating: 9, recommendation: "Excellent source of healthy monounsaturated fats and potassium." },
  { id: 21, name: "Raspberry", category: "Fruits", calories: 52, protein: "1.2g", carbs: "11.9g", fats: "0.7g", healthRating: 9, recommendation: "Extremely high in fiber and keeps blood sugar stable." },
  { id: 22, name: "Blackberry", category: "Fruits", calories: 43, protein: "1.4g", carbs: "9.6g", fats: "0.5g", healthRating: 9, recommendation: "Rich in bioflavonoids and vitamin C. Good skin support." },
  { id: 23, name: "Coconut", category: "Fruits", calories: 354, protein: "3.3g", carbs: "15.2g", fats: "33.5g", healthRating: 7, recommendation: "High in healthy saturated fats (MCTs) but calorie dense." },
  { id: 24, name: "Lemon", category: "Fruits", calories: 29, protein: "1.1g", carbs: "9.3g", fats: "0.3g", healthRating: 9, recommendation: "Excellent alkalizing agent. Promotes digestion and skin glow." },
  { id: 25, name: "Lime", category: "Fruits", calories: 30, protein: "0.7g", carbs: "10.5g", fats: "0.2g", healthRating: 9, recommendation: "Boosts immune system. Adds calorie-free flavor to drinks." },
  { id: 26, name: "Musk Melon", category: "Fruits", calories: 34, protein: "0.8g", carbs: "8.2g", fats: "0.2g", healthRating: 9, recommendation: "Very refreshing and hydrating. High in vitamin A." },
  { id: 27, name: "Sweet Lime", category: "Fruits", calories: 43, protein: "0.8g", carbs: "9.3g", fats: "0.3g", healthRating: 9, recommendation: "Excellent juice fruit for hydration and body detoxification." },
  { id: 28, name: "Custard Apple", category: "Fruits", calories: 94, protein: "2.1g", carbs: "23.6g", fats: "0.6g", healthRating: 7, recommendation: "Rich in magnesium and iron, but eat in moderation." },
  { id: 29, name: "Sapodilla", category: "Fruits", calories: 83, protein: "0.4g", carbs: "20g", fats: "1.1g", healthRating: 7, recommendation: "Provides instant energy and fiber. High in natural sugars." },
  { id: 30, name: "Jackfruit", category: "Fruits", calories: 95, protein: "1.7g", carbs: "23.2g", fats: "0.6g", healthRating: 8, recommendation: "Great meat substitute in raw form. Rich in B vitamins." },

  // Vegetables
  { id: 31, name: "Potato", category: "Vegetables", calories: 77, protein: "2g", carbs: "17g", fats: "0.1g", healthRating: 7, recommendation: "Nutritious root veg. Avoid deep frying. Best boiled or baked." },
  { id: 32, name: "Tomato", category: "Vegetables", calories: 18, protein: "0.9g", carbs: "3.9g", fats: "0.2g", healthRating: 9, recommendation: "Rich source of lycopene, supporting heart health and skin." },
  { id: 33, name: "Onion", category: "Vegetables", calories: 40, protein: "1.1g", carbs: "9.3g", fats: "0.1g", healthRating: 9, recommendation: "Contains prebiotics and antioxidants. Promotes gut health." },
  { id: 34, name: "Carrot", category: "Vegetables", calories: 41, protein: "0.9g", carbs: "9.6g", fats: "0.2g", healthRating: 10, recommendation: "Outstanding source of beta-carotene, crucial for eye health." },
  { id: 35, name: "Spinach", category: "Vegetables", calories: 23, protein: "2.9g", carbs: "3.6g", fats: "0.4g", healthRating: 10, recommendation: "Nutritional powerhouse rich in iron, calcium, and folate." },
  { id: 36, name: "Cauliflower", category: "Vegetables", calories: 25, protein: "1.9g", carbs: "5g", fats: "0.3g", healthRating: 9, recommendation: "Low carb, high fiber cruciferous vegetable. Great rice swap." },
  { id: 37, name: "Broccoli", category: "Vegetables", calories: 34, protein: "2.8g", carbs: "6.6g", fats: "0.4g", healthRating: 10, recommendation: "High in sulforaphane, which offers strong anti-cancer benefits." },
  { id: 38, name: "Cabbage", category: "Vegetables", calories: 25, protein: "1.3g", carbs: "5.8g", fats: "0.1g", healthRating: 9, recommendation: "Inexpensive source of vitamins C and K. Promotes digestion." },
  { id: 39, name: "Green Peas", category: "Vegetables", calories: 81, protein: "5.4g", carbs: "14.4g", fats: "0.4g", healthRating: 8, recommendation: "Good plant-based protein source. High in fiber." },
  { id: 40, name: "Cucumber", category: "Vegetables", calories: 15, protein: "0.7g", carbs: "3.6g", fats: "0.1g", healthRating: 9, recommendation: "Very hydrating and low calorie. Perfect salad base." },
  { id: 41, name: "Capsicum", category: "Vegetables", calories: 20, protein: "0.9g", carbs: "4.6g", fats: "0.2g", healthRating: 9, recommendation: "High in antioxidants and vitamin C. Boosts metabolism." },
  { id: 42, name: "Beetroot", category: "Vegetables", calories: 43, protein: "1.6g", carbs: "9.6g", fats: "0.2g", healthRating: 9, recommendation: "Increases blood flow and exercise stamina due to nitrates." },
  { id: 43, name: "Garlic", category: "Vegetables", calories: 149, protein: "6.4g", carbs: "33g", fats: "0.5g", healthRating: 10, recommendation: "Powerful antibacterial and antiviral properties. Lowers BP." },
  { id: 44, name: "Ginger", category: "Vegetables", calories: 80, protein: "1.8g", carbs: "17.8g", fats: "0.8g", healthRating: 10, recommendation: "Reduces nausea and acts as a potent anti-inflammatory." },
  { id: 45, name: "Mushroom", category: "Vegetables", calories: 22, protein: "3.1g", carbs: "3.3g", fats: "0.3g", healthRating: 9, recommendation: "Low calorie, high selenium. Great immune booster." },
  { id: 46, name: "Ladies Finger", category: "Vegetables", calories: 33, protein: "1.9g", carbs: "7.5g", fats: "0.2g", healthRating: 9, recommendation: "Rich in mucilage which aids digestion and controls sugars." },
  { id: 47, name: "Eggplant", category: "Vegetables", calories: 25, protein: "1g", carbs: "6g", fats: "0.2g", healthRating: 8, recommendation: "Good source of nasunin, an antioxidant protecting brain cells." },
  { id: 48, name: "Bottle Gourd", category: "Vegetables", calories: 15, protein: "0.6g", carbs: "3.4g", fats: "0.1g", healthRating: 9, recommendation: "Highly cooling and easy to digest. Ideal during illness." },
  { id: 49, name: "Pumpkin", category: "Vegetables", calories: 26, protein: "1g", carbs: "6.5g", fats: "0.1g", healthRating: 9, recommendation: "Loaded with vitamin A. Low-calorie and satisfying." },
  { id: 50, name: "Radish", category: "Vegetables", calories: 16, protein: "0.7g", carbs: "3.4g", fats: "0.1g", healthRating: 8, recommendation: "Good detoxification agent. Lowers blood pressure." },
  { id: 51, name: "Sweet Potato", category: "Vegetables", calories: 86, protein: "1.6g", carbs: "20.1g", fats: "0.1g", healthRating: 9, recommendation: "Rich in complex carbs, vitamin A, and fiber. Stable energy." },
  { id: 52, name: "Bitter Gourd", category: "Vegetables", calories: 17, protein: "1g", carbs: "3.7g", fats: "0.2g", healthRating: 9, recommendation: "Outstanding for blood sugar regulation and insulin control." },
  { id: 53, name: "Fenugreek Leaves", category: "Vegetables", calories: 49, protein: "4.4g", carbs: "6g", fats: "0.9g", healthRating: 9, recommendation: "Helps control cholesterol and improves insulin response." },
  { id: 54, name: "Coriander Leaves", category: "Vegetables", calories: 23, protein: "2.1g", carbs: "3.7g", fats: "0.5g", healthRating: 9, recommendation: "Helps flush heavy metals out of the body. Digestive aid." },
  { id: 55, name: "Mint Leaves", category: "Vegetables", calories: 44, protein: "3.2g", carbs: "8.4g", fats: "0.6g", healthRating: 9, recommendation: "Calms irritable bowel syndrome and refreshes breath." },
  { id: 56, name: "Curry Leaves", category: "Vegetables", calories: 108, protein: "6g", carbs: "18.7g", fats: "1g", healthRating: 9, recommendation: "Great for hair health and glycemic management." },
  { id: 57, name: "Asparagus", category: "Vegetables", calories: 20, protein: "2.2g", carbs: "3.9g", fats: "0.1g", healthRating: 9, recommendation: "Natural diuretic, supports urinary tract health." },
  { id: 58, name: "Celery", category: "Vegetables", calories: 16, protein: "0.7g", carbs: "3g", fats: "0.2g", healthRating: 9, recommendation: "Virtually zero calories. Provides high hydration." },
  { id: 59, name: "Zucchini", category: "Vegetables", calories: 17, protein: "1.2g", carbs: "3.1g", fats: "0.3g", healthRating: 9, recommendation: "Low carb vegetable. Ideal for creating noodles (zoodles)." },
  { id: 60, name: "Spring Onion", category: "Vegetables", calories: 32, protein: "1.8g", carbs: "7.3g", fats: "0.2g", healthRating: 9, recommendation: "High in vitamin K. Improves bone strength." },

  // Indian Meals
  { id: 61, name: "Rice", category: "Indian Meals", calories: 130, protein: "2.7g", carbs: "28g", fats: "0.3g", healthRating: 7, recommendation: "Provides clean energy. Prefer brown or unpolished rice." },
  { id: 62, name: "Dal", category: "Indian Meals", calories: 150, protein: "9g", carbs: "22g", fats: "2.5g", healthRating: 9, recommendation: "Protein and fiber rich daily meal. Essential amino acids." },
  { id: 63, name: "Roti", category: "Indian Meals", calories: 104, protein: "3.5g", carbs: "22g", fats: "0.5g", healthRating: 8, recommendation: "Good source of fiber. Eat without heavy butter or ghee." },
  { id: 64, name: "Paneer Masala", category: "Indian Meals", calories: 310, protein: "14g", carbs: "12g", fats: "23g", healthRating: 7, recommendation: "Excellent vegetarian protein. Control oil and cream." },
  { id: 65, name: "Rajma Chawal", category: "Indian Meals", calories: 420, protein: "15g", carbs: "75g", fats: "5g", healthRating: 8, recommendation: "Nutritious protein-carb combo. High in dietary fiber." },
  { id: 66, name: "Chole Bhature", category: "Indian Meals", calories: 650, protein: "12g", carbs: "80g", fats: "30g", healthRating: 3, recommendation: "Heavy, deep-fried meal. Consume rarely." },
  { id: 67, name: "Khichdi", category: "Indian Meals", calories: 250, protein: "8g", carbs: "48g", fats: "3g", healthRating: 9, recommendation: "Extremely easy to digest. Perfect light, balanced meal." },
  { id: 68, name: "Vegetable Biryani", category: "Indian Meals", calories: 350, protein: "8g", carbs: "62g", fats: "8g", healthRating: 7, recommendation: "Savory meal. Monitor portion size and oil usage." },
  { id: 69, name: "Chicken Biryani", category: "Indian Meals", calories: 480, protein: "24g", carbs: "68g", fats: "12g", healthRating: 7, recommendation: "High protein, but also high calorie. Control portions." },
  { id: 70, name: "Palak Paneer", category: "Indian Meals", calories: 220, protein: "12g", carbs: "8g", fats: "16g", healthRating: 9, recommendation: "Vitamins and protein packed. Highly recommended health meal." },
  { id: 71, name: "Aloo Gobi", category: "Indian Meals", calories: 150, protein: "3g", carbs: "18g", fats: "7g", healthRating: 7, recommendation: "Good everyday vegetable, cook with minimal oil." },
  { id: 72, name: "Bhindi Masala", category: "Indian Meals", calories: 120, protein: "2.5g", carbs: "12g", fats: "6g", healthRating: 8, recommendation: "Healthy fiber-rich side dish. Do not overcook." },
  { id: 73, name: "Kadhi Pakoda", category: "Indian Meals", calories: 290, protein: "8g", carbs: "32g", fats: "14g", healthRating: 6, recommendation: "Tasty curd-based dish. Limit fried pakodas to save fat." },
  { id: 74, name: "Butter Chicken", category: "Indian Meals", calories: 490, protein: "30g", carbs: "14g", fats: "35g", healthRating: 4, recommendation: "Very high in fats and heavy cream. Limit intake." },
  { id: 75, name: "Fish Curry", category: "Indian Meals", calories: 280, protein: "26g", carbs: "6g", fats: "16g", healthRating: 8, recommendation: "Excellent source of omega-3 and lean protein." },
  { id: 76, name: "Chicken Tikka", category: "Indian Meals", calories: 240, protein: "32g", carbs: "4g", fats: "10g", healthRating: 8, recommendation: "Tandoori preparation. High protein, moderate fat." },
  { id: 77, name: "Egg Curry", category: "Indian Meals", calories: 260, protein: "13g", carbs: "8g", fats: "18g", healthRating: 8, recommendation: "High protein and essential nutrients. Keep oil low." },
  { id: 78, name: "Sambhar", category: "Indian Meals", calories: 110, protein: "4g", carbs: "18g", fats: "2g", healthRating: 9, recommendation: "Lentil soup with lots of veggies. Excellent daily food." },
  { id: 79, name: "Rasam", category: "Indian Meals", calories: 60, protein: "1.5g", carbs: "10g", fats: "1.5g", healthRating: 9, recommendation: "Light, spicy soup. Speeds digestion and boosts immunity." },
  { id: 80, name: "Masala Dosa", category: "Indian Meals", calories: 350, protein: "6g", carbs: "55g", fats: "12g", healthRating: 6, recommendation: "Yummy fermented meal. Potato filling adds carbs." },
  { id: 81, name: "Uttapam", category: "Indian Meals", calories: 260, protein: "6g", carbs: "45g", fats: "6g", healthRating: 8, recommendation: "Fermented rice pancake. Top with lots of raw veggies." },
  { id: 82, name: "Veg Pulao", category: "Indian Meals", calories: 280, protein: "6g", carbs: "52g", fats: "5g", healthRating: 8, recommendation: "Light rice meal. Add peas, carrots, beans for fiber." },
  { id: 83, name: "Paneer Bhurji", category: "Indian Meals", calories: 240, protein: "15g", carbs: "6g", fats: "18g", healthRating: 8, recommendation: "Quick, high protein low-carb vegetarian meal." },
  { id: 84, name: "Aloo Methi", category: "Indian Meals", calories: 160, protein: "3.5g", carbs: "20g", fats: "7g", healthRating: 7, recommendation: "Combines nutrients of fenugreek leaves with potato carbs." },
  { id: 85, name: "Egg Bhurji", category: "Indian Meals", calories: 220, protein: "14g", carbs: "4g", fats: "16g", healthRating: 8, recommendation: "Excellent high-protein quick breakfast or meal option." },
  { id: 86, name: "Curd Rice", category: "Indian Meals", calories: 230, protein: "6g", carbs: "38g", fats: "5g", healthRating: 9, recommendation: "Extremely cooling for stomach. Promotes healthy gut microbiome." },
  { id: 87, name: "Lemon Rice", category: "Indian Meals", calories: 270, protein: "5g", carbs: "48g", fats: "6g", healthRating: 7, recommendation: "Tangy rice dish. Serve with curd for a protein balance." },
  { id: 88, name: "Pongal", category: "Indian Meals", calories: 320, protein: "8g", carbs: "54g", fats: "8g", healthRating: 8, recommendation: "Classic rice-lentil dish. Highly comforting and nutritious." },
  { id: 89, name: "Sarson Ka Saag", category: "Indian Meals", calories: 140, protein: "4g", carbs: "12g", fats: "8g", healthRating: 9, recommendation: "Highly nutritious mustard greens. Serve hot." },
  { id: 90, name: "Makki Di Roti", category: "Indian Meals", calories: 150, protein: "3g", carbs: "28g", fats: "2.5g", healthRating: 7, recommendation: "Corn flour flatbread. High energy, moderate fiber." },

  // Indian Snacks
  { id: 91, name: "Samosa", category: "Indian Snacks", calories: 262, protein: "4g", carbs: "31g", fats: "14g", healthRating: 4, recommendation: "Occasional food. High oil content from deep frying." },
  { id: 92, name: "Kachori", category: "Indian Snacks", calories: 380, protein: "6g", carbs: "42g", fats: "21g", healthRating: 3, recommendation: "Deep-fried, refined flour snack. Eat very sparingly." },
  { id: 93, name: "Poha", category: "Indian Snacks", calories: 250, protein: "4g", carbs: "45g", fats: "5g", healthRating: 8, recommendation: "Light breakfast. Cook with lots of vegetables and peanuts." },
  { id: 94, name: "Upma", category: "Indian Snacks", calories: 210, protein: "5g", carbs: "38g", fats: "4g", healthRating: 7, recommendation: "Good semolina snack. Add veggies to lower glycemic load." },
  { id: 95, name: "Dhokla", category: "Indian Snacks", calories: 160, protein: "6g", carbs: "24g", fats: "4g", healthRating: 8, recommendation: "Steamed snack. High protein, low fat, easy to digest." },
  { id: 96, name: "Khandvi", category: "Indian Snacks", calories: 120, protein: "4g", carbs: "16g", fats: "4.5g", healthRating: 8, recommendation: "Steamed chickpea flour rolls. Low calorie healthy snack." },
  { id: 97, name: "Pakora", category: "Indian Snacks", calories: 280, protein: "5g", carbs: "25g", fats: "18g", healthRating: 4, recommendation: "Deep-fried. Limit intake due to high absorption of oil." },
  { id: 98, name: "Bhel Puri", category: "Indian Snacks", calories: 180, protein: "4g", carbs: "32g", fats: "3.5g", healthRating: 7, recommendation: "Light snack. Limit sweet chutneys to keep sugars down." },
  { id: 99, name: "Sev Puri", category: "Indian Snacks", calories: 310, protein: "5g", carbs: "42g", fats: "14g", healthRating: 5, recommendation: "Tasty street snack. High in refined carbs and fried sev." },
  { id: 100, name: "Pani Puri", category: "Indian Snacks", calories: 150, protein: "3g", carbs: "25g", fats: "4g", healthRating: 6, recommendation: "Moderate calories. Keep water clean and limit sweet chutney." },
  { id: 101, name: "Aloo Tikki", category: "Indian Snacks", calories: 220, protein: "3g", carbs: "28g", fats: "11g", healthRating: 5, recommendation: "Fried potato patty. Limit sweet toppings." },
  { id: 102, name: "Pav Bhaji", category: "Indian Snacks", calories: 450, protein: "9g", carbs: "62g", fats: "18g", healthRating: 5, recommendation: "Veggies are healthy, but pav is refined bread. Limit butter." },
  { id: 103, name: "Vada Pav", category: "Indian Snacks", calories: 300, protein: "6g", carbs: "44g", fats: "11g", healthRating: 4, recommendation: "High carb, deep fried potato snack. Avoid daily use." },
  { id: 104, name: "Papdi Chaat", category: "Indian Snacks", calories: 330, protein: "6g", carbs: "48g", fats: "13g", healthRating: 5, recommendation: "High in sodium and refined flour crackers. Eat occasionally." },
  { id: 105, name: "Dahi Vada", category: "Indian Snacks", calories: 280, protein: "8g", carbs: "34g", fats: "12g", healthRating: 7, recommendation: "Cooling yogurt snack. Opt for non-fried/soaked vadas." },
  { id: 106, name: "Murukku", category: "Indian Snacks", calories: 150, protein: "2.5g", carbs: "18g", fats: "8g", healthRating: 4, recommendation: "Crunchy fried snack. Extremely easy to overeat." },
  { id: 107, name: "Chakli", category: "Indian Snacks", calories: 160, protein: "3g", carbs: "20g", fats: "8g", healthRating: 4, recommendation: "Fried flour snack. Portion control is essential." },
  { id: 108, name: "Namkeen", category: "Indian Snacks", calories: 170, protein: "4g", carbs: "15g", fats: "11g", healthRating: 4, recommendation: "High in sodium and saturated fats. Substitute with dry fruits." },
  { id: 109, name: "Mathri", category: "Indian Snacks", calories: 180, protein: "3g", carbs: "22g", fats: "9g", healthRating: 4, recommendation: "Fried wheat flour crackers. High in trans fats if not homemade." },
  { id: 110, name: "Medu Vada", category: "Indian Snacks", calories: 220, protein: "6g", carbs: "24g", fats: "11g", healthRating: 5, recommendation: "Crispy fried lentil donut. Limit portion size." },
  { id: 111, name: "Sabudana Vada", category: "Indian Snacks", calories: 280, protein: "2g", carbs: "42g", fats: "12g", healthRating: 4, recommendation: "Starchy tapioca pearls deep fried. High in carbs." },
  { id: 112, name: "Banana Chips", category: "Indian Snacks", calories: 150, protein: "1g", carbs: "18g", fats: "9g", healthRating: 5, recommendation: "Deep-fried. Looks healthy, but high in fat and calories." },
  { id: 113, name: "Gathiya", category: "Indian Snacks", calories: 160, protein: "4g", carbs: "14g", fats: "10g", healthRating: 4, recommendation: "Deep fried chickpea flour snack. High sodium content." },
  { id: 114, name: "Sev", category: "Indian Snacks", calories: 160, protein: "3.5g", carbs: "15g", fats: "10g", healthRating: 4, recommendation: "Fried chickpea flour strings. Use sparingly as garnish." },
  { id: 115, name: "Khakhra", category: "Indian Snacks", calories: 90, protein: "3g", carbs: "16g", fats: "1.5g", healthRating: 8, recommendation: "Roasted whole wheat cracker. Healthy low-calorie snack." },
  { id: 116, name: "Bhakarwadi", category: "Indian Snacks", calories: 150, protein: "2.5g", carbs: "18g", fats: "8g", healthRating: 4, recommendation: "Sweet and spicy fried roll. Portions must be monitored." },
  { id: 117, name: "Jhal Muri", category: "Indian Snacks", calories: 140, protein: "3g", carbs: "22g", fats: "4g", healthRating: 8, recommendation: "Spiced puffed rice snack. Low fat and very filling." },
  { id: 118, name: "Chana Chaat", category: "Indian Snacks", calories: 190, protein: "8g", carbs: "30g", fats: "3g", healthRating: 9, recommendation: "Highly nutritious, fiber-rich boiled chickpea snack." },
  { id: 119, name: "Paneer Tikka", category: "Indian Snacks", calories: 180, protein: "12g", carbs: "6g", fats: "12g", healthRating: 9, recommendation: "Grilled cottage cheese with herbs. High protein, excellent snack." },
  { id: 120, name: "Veg Cutlet", category: "Indian Snacks", calories: 160, protein: "3g", carbs: "22g", fats: "7g", healthRating: 6, recommendation: "Pan-fried vegetable patty. Opt for baking or air-frying." },

  // Fast Food
  { id: 121, name: "Burger", category: "Fast Food", calories: 295, protein: "13g", carbs: "30g", fats: "14g", healthRating: 5, recommendation: "Process-heavy fast food. Limit consumption." },
  { id: 122, name: "Pizza", category: "Fast Food", calories: 285, protein: "12g", carbs: "32g", fats: "12g", healthRating: 5, recommendation: "High in sodium and saturated cheese fat. Choose thin crust." },
  { id: 123, name: "French Fries", category: "Fast Food", calories: 312, protein: "3.4g", carbs: "41g", fats: "15g", healthRating: 3, recommendation: "Fried starch. High trans fats. Limit strictly." },
  { id: 124, name: "Pasta", category: "Fast Food", calories: 220, protein: "8g", carbs: "43g", fats: "1.5g", healthRating: 7, recommendation: "Control portions. Use red sauce instead of creamy white sauce." },
  { id: 125, name: "Noodles", category: "Fast Food", calories: 380, protein: "9g", carbs: "52g", fats: "15g", healthRating: 4, recommendation: "High in refined wheat and oil. Keep veggies high." },
  { id: 126, name: "Garlic Bread", category: "Fast Food", calories: 350, protein: "9g", carbs: "42g", fats: "16g", healthRating: 4, recommendation: "High refined carbs and saturated butter fat. Eat sparingly." },
  { id: 127, name: "Cheese Sandwich", category: "Fast Food", calories: 320, protein: "12g", carbs: "28g", fats: "18g", healthRating: 5, recommendation: "Quick meal. Use whole grain bread and limit cheese." },
  { id: 128, name: "Hot Dog", category: "Fast Food", calories: 290, protein: "10g", carbs: "24g", fats: "16g", healthRating: 3, recommendation: "Processed meat. High sodium and preservatives. Limit intake." },
  { id: 129, name: "Chicken Nuggets", category: "Fast Food", calories: 296, protein: "16g", carbs: "15g", fats: "18g", healthRating: 4, recommendation: "Deep-fried processed chicken. Moderate protein, high fat." },
  { id: 130, name: "Spring Roll", category: "Fast Food", calories: 180, protein: "3.5g", carbs: "24g", fats: "8g", healthRating: 4, recommendation: "Deep-fried wrapper. High oil content." },
  { id: 131, name: "Momos", category: "Fast Food", calories: 150, protein: "4g", carbs: "28g", fats: "2g", healthRating: 6, recommendation: "Steamed. Refined flour outer shell. Control dipping sauce." },
  { id: 132, name: "Club Sandwich", category: "Fast Food", calories: 480, protein: "22g", carbs: "48g", fats: "22g", healthRating: 6, recommendation: "Heavy meal. Omit mayonnaise to lower calorie density." },
  { id: 133, name: "Taco", category: "Fast Food", calories: 220, protein: "10g", carbs: "20g", fats: "11g", healthRating: 6, recommendation: "Control cheese and sour cream. Load with salsa and beans." },
  { id: 134, name: "Quesadilla", category: "Fast Food", calories: 380, protein: "16g", carbs: "32g", fats: "20g", healthRating: 5, recommendation: "High in cheese and refined flour. Share portions." },
  { id: 135, name: "Waffles", category: "Fast Food", calories: 290, protein: "6g", carbs: "41g", fats: "11g", healthRating: 4, recommendation: "High in sugar and simple carbs. Serve without heavy syrups." },
  { id: 136, name: "Pancake", category: "Fast Food", calories: 227, protein: "6g", carbs: "28g", fats: "10g", healthRating: 5, recommendation: "Refined flour base. Limit butter and maple syrup." },
  { id: 137, name: "Donut", category: "Fast Food", calories: 452, protein: "4.9g", carbs: "51g", fats: "25g", healthRating: 2, recommendation: "Deep fried dough with high sugar. Very poor health value." },
  { id: 138, name: "Onion Rings", category: "Fast Food", calories: 411, protein: "4g", carbs: "48g", fats: "22g", healthRating: 2, recommendation: "Deep-fried batter. Extreme fat absorption." },
  { id: 139, name: "Mozzarella Sticks", category: "Fast Food", calories: 320, protein: "14g", carbs: "24g", fats: "18g", healthRating: 3, recommendation: "Deep fried cheese. High in sodium and saturated fats." },
  { id: 140, name: "Garlic Knots", category: "Fast Food", calories: 310, protein: "7g", carbs: "48g", fats: "10g", healthRating: 4, recommendation: "Refined pizza dough rolled in butter and garlic. High carbs." },
  { id: 141, name: "Chicken Wings", category: "Fast Food", calories: 290, protein: "24g", carbs: "0g", fats: "21g", healthRating: 5, recommendation: "Portion control. Baked is much healthier than fried." },
  { id: 142, name: "Cheeseburger", category: "Fast Food", calories: 320, protein: "15g", carbs: "30g", fats: "16g", healthRating: 4, recommendation: "Fast food staple. Contains processed ingredients." },
  { id: 143, name: "Margherita Pizza", category: "Fast Food", calories: 250, protein: "11g", carbs: "30g", fats: "10g", healthRating: 6, recommendation: "Simple pizza. Control slices and dough thickness." },
  { id: 144, name: "Mac and Cheese", category: "Fast Food", calories: 370, protein: "13g", carbs: "48g", fats: "14g", healthRating: 4, recommendation: "Refined pasta and cheese blend. Low in fiber." },
  { id: 145, name: "Shawarma", category: "Fast Food", calories: 390, protein: "26g", carbs: "36g", fats: "16g", healthRating: 6, recommendation: "Good protein, but mayo/sauces add hidden fats." },
  { id: 146, name: "Pasta Alfredo", category: "Fast Food", calories: 540, protein: "15g", carbs: "58g", fats: "28g", healthRating: 4, recommendation: "White sauce based on heavy cream and butter. Calorie bomb." },
  { id: 147, name: "Veg Chowmein", category: "Fast Food", calories: 320, protein: "7g", carbs: "50g", fats: "11g", healthRating: 5, recommendation: "Tasty but oily street-style noodles. Limit intake." },
  { id: 148, name: "Hakka Noodles", category: "Fast Food", calories: 290, protein: "6g", carbs: "48g", fats: "8g", healthRating: 5, recommendation: "Lighter than street chowmein. Load with crunchy cabbage." },
  { id: 149, name: "Chicken Momos", category: "Fast Food", calories: 190, protein: "12g", carbs: "25g", fats: "4g", healthRating: 6, recommendation: "Steamed chicken dumplings. Good protein, moderate carbs." },
  { id: 150, name: "Garlic Bread with Cheese", category: "Fast Food", calories: 420, protein: "14g", carbs: "44g", fats: "20g", healthRating: 3, recommendation: "High fat, high calorie side. Share or skip." },

  // Dairy
  { id: 151, name: "Milk", category: "Dairy", calories: 122, protein: "8g", carbs: "12g", fats: "5g", healthRating: 8, recommendation: "Good source of calcium and protein. Opt for skimmed if dieting." },
  { id: 152, name: "Curd", category: "Dairy", calories: 98, protein: "11g", carbs: "3.4g", fats: "4.3g", healthRating: 10, recommendation: "Outstanding probiotic. Enhances gut health and digestion." },
  { id: 153, name: "Butter", category: "Dairy", calories: 717, protein: "0.9g", carbs: "0.1g", fats: "81g", healthRating: 5, recommendation: "Pure fat. Use in small quantities only." },
  { id: 154, name: "Cheese", category: "Dairy", calories: 402, protein: "25g", carbs: "1.3g", fats: "33g", healthRating: 6, recommendation: "Excellent calcium but high in saturated fat and sodium." },
  { id: 155, name: "Milk Whole", category: "Dairy", calories: 149, protein: "8g", carbs: "12g", fats: "8g", healthRating: 8, recommendation: "Provides essential vitamins D and A. Good for children." },
  { id: 156, name: "Milk Skimmed", category: "Dairy", calories: 83, protein: "8.3g", carbs: "12g", fats: "0.2g", healthRating: 9, recommendation: "High calcium, virtually zero fat. Great for calorie control." },
  { id: 157, name: "Greek Yogurt", category: "Dairy", calories: 100, protein: "10g", carbs: "3.6g", fats: "5g", healthRating: 10, recommendation: "Thick, high protein yogurt. Excellent post-workout snack." },
  { id: 158, name: "Paneer", category: "Dairy", calories: 265, protein: "18.3g", carbs: "1.2g", fats: "20.8g", healthRating: 9, recommendation: "Excellent vegetarian protein. Good calcium source." },
  { id: 159, name: "Ghee", category: "Dairy", calories: 884, protein: "0g", carbs: "0g", fats: "100g", healthRating: 7, recommendation: "Healthy fats (butyric acid) but extremely calorie dense." },
  { id: 160, name: "Buttermilk", category: "Dairy", calories: 40, protein: "3g", carbs: "4.8g", fats: "0.9g", healthRating: 10, recommendation: "Incredibly refreshing and probiotic. Low-calorie digestion aid." },
  { id: 161, name: "Lassi Sweet", category: "Dairy", calories: 200, protein: "5g", carbs: "32g", fats: "6g", healthRating: 7, recommendation: "Satisfying, but check added sugar content." },
  { id: 162, name: "Lassi Salted", category: "Dairy", calories: 110, protein: "5g", carbs: "8g", fats: "6g", healthRating: 9, recommendation: "Great probiotic drink. Perfect cooling summer beverage." },
  { id: 163, name: "Whipping Cream", category: "Dairy", calories: 345, protein: "2g", carbs: "2.8g", fats: "37g", healthRating: 4, recommendation: "High saturated fats. Use minimally in cooking." },
  { id: 164, name: "Condensed Milk", category: "Dairy", calories: 321, protein: "8g", carbs: "54g", fats: "9g", healthRating: 4, recommendation: "Very high sugar and calorie content. Use sparingly." },
  { id: 165, name: "Ice Cream Vanilla", category: "Dairy", calories: 207, protein: "3.5g", carbs: "24g", fats: "11g", healthRating: 4, recommendation: "High sugar sweet dessert. Treat occasionally." },
  { id: 166, name: "Cottage Cheese", category: "Dairy", calories: 98, protein: "11g", carbs: "3.4g", fats: "4.3g", healthRating: 9, recommendation: "Low calorie, slow-digesting casein protein. Great before bed." },
  { id: 167, name: "Margarine", category: "Dairy", calories: 717, protein: "0g", carbs: "0g", fats: "81g", healthRating: 5, recommendation: "Processed butter swap. Check for trans fats." },
  { id: 168, name: "Goat Cheese", category: "Dairy", calories: 364, protein: "22g", carbs: "0.1g", fats: "30g", healthRating: 8, recommendation: "Easier to digest than cow milk cheese for some." },
  { id: 169, name: "Sour Cream", category: "Dairy", calories: 198, protein: "2.4g", carbs: "4.6g", fats: "19g", healthRating: 6, recommendation: "Moderate calories. Limit toppings on tacos." },
  { id: 170, name: "Cream Cheese", category: "Dairy", calories: 342, protein: "6g", carbs: "4.1g", fats: "34g", healthRating: 5, recommendation: "Spread in thin layers on bagels to manage fat load." },
  { id: 171, name: "Feta Cheese", category: "Dairy", calories: 264, protein: "14g", carbs: "4g", fats: "21g", healthRating: 7, recommendation: "Crumbly salad cheese. Good flavor, high sodium." },
  { id: 172, name: "Parmesan Cheese", category: "Dairy", calories: 431, protein: "38g", carbs: "4.1g", fats: "29g", healthRating: 7, recommendation: "Hard cheese with high protein density. High sodium." },
  { id: 173, name: "Ricotta Cheese", category: "Dairy", calories: 174, protein: "11g", carbs: "3g", fats: "13g", healthRating: 8, recommendation: "Whey-rich light cheese. Excellent for cooking." },
  { id: 174, name: "Paneer Low Fat", category: "Dairy", calories: 180, protein: "20g", carbs: "2g", fats: "10g", healthRating: 10, recommendation: "Amazing high protein, low fat veggie choice." },
  { id: 175, name: "Yakult", category: "Dairy", calories: 50, protein: "0.8g", carbs: "12g", fats: "0.1g", healthRating: 8, recommendation: "Probiotic shot. Helps gut wellness, contains sugars." },
  { id: 176, name: "Mozzarella Cheese", category: "Dairy", calories: 280, protein: "22g", carbs: "2g", fats: "20g", healthRating: 7, recommendation: "Melts beautifully. Moderate protein, lower fat than cheddar." },
  { id: 177, name: "Soy Milk", category: "Dairy", calories: 54, protein: "3.3g", carbs: "6g", fats: "1.8g", healthRating: 9, recommendation: "Dairy-free alternative with similar protein levels to cow milk." },
  { id: 178, name: "Almond Milk", category: "Dairy", calories: 15, protein: "0.6g", carbs: "0.3g", fats: "1.1g", healthRating: 8, recommendation: "Unsweetened is very low in calories, but low in protein." },
  { id: 179, name: "Oat Milk", category: "Dairy", calories: 50, protein: "1g", carbs: "9g", fats: "1.5g", healthRating: 7, recommendation: "Creamy vegan alternative. Higher in carbs than almond milk." },
  { id: 180, name: "Coconut Milk", category: "Dairy", calories: 230, protein: "2.3g", carbs: "6g", fats: "24g", healthRating: 7, recommendation: "Rich in lauric acid. Great flavor, high fat density." },

  // Beverages
  { id: 181, name: "Tea", category: "Beverages", calories: 2, protein: "0.1g", carbs: "0.2g", fats: "0g", healthRating: 9, recommendation: "Rich in antioxidants. Avoid adding too much sugar or milk." },
  { id: 182, name: "Coffee", category: "Beverages", calories: 2, protein: "0.3g", carbs: "0g", fats: "0.05g", healthRating: 9, recommendation: "Boosts metabolism. Drink black or with minimal milk/sugar." },
  { id: 183, name: "Coconut Water", category: "Beverages", calories: 19, protein: "0.7g", carbs: "3.7g", fats: "0.2g", healthRating: 10, recommendation: "Nature's sports drink. Rich in electrolytes and potassium." },
  { id: 184, name: "Lassi", category: "Beverages", calories: 150, protein: "4g", carbs: "24g", fats: "4g", healthRating: 8, recommendation: "Filling yogurt drink. Opt for salted or sugar-free." },
  { id: 185, name: "Chaas", category: "Beverages", calories: 35, protein: "2.5g", carbs: "4g", fats: "0.8g", healthRating: 10, recommendation: "Spiced buttermilk. Superb for hydration and digestion." },
  { id: 186, name: "Green Tea", category: "Beverages", calories: 2, protein: "0g", carbs: "0g", fats: "0g", healthRating: 10, recommendation: "High in EGCG catechins. Speeds fat loss and brain function." },
  { id: 187, name: "Lemonade", category: "Beverages", calories: 40, protein: "0.1g", carbs: "10g", fats: "0.1g", healthRating: 7, recommendation: "Good vitamin C. Limit table sugar additives." },
  { id: 188, name: "Orange Juice", category: "Beverages", calories: 45, protein: "0.7g", carbs: "10.4g", fats: "0.2g", healthRating: 8, recommendation: "High vitamin C, but lacks whole fruit fiber." },
  { id: 189, name: "Apple Juice", category: "Beverages", calories: 46, protein: "0.1g", carbs: "11.3g", fats: "0.1g", healthRating: 7, recommendation: "Fruit sugar source. Whole apples are much healthier." },
  { id: 190, name: "Sugarcane Juice", category: "Beverages", calories: 270, protein: "1g", carbs: "70g", fats: "0.2g", healthRating: 6, recommendation: "Instant energy drink. Very high glycemic index." },
  { id: 191, name: "Soft Drink", category: "Beverages", calories: 140, protein: "0g", carbs: "39g", fats: "0g", healthRating: 1, recommendation: "Empty sugar calories. Highly damaging to health. Avoid." },
  { id: 192, name: "Energy Drink", category: "Beverages", calories: 110, protein: "0g", carbs: "28g", fats: "0g", healthRating: 2, recommendation: "High caffeine and synthetic sugar. Overtaxing for heart." },
  { id: 193, name: "Milkshake Chocolate", category: "Beverages", calories: 350, protein: "8g", carbs: "60g", fats: "10g", healthRating: 4, recommendation: "High sugar dessert beverage. Treat occasionally." },
  { id: 194, name: "Milkshake Mango", category: "Beverages", calories: 320, protein: "7g", carbs: "54g", fats: "9g", healthRating: 5, recommendation: "Mango flavor with milk and sugar. Portion control." },
  { id: 195, name: "Milkshake Strawberry", category: "Beverages", calories: 310, protein: "7g", carbs: "52g", fats: "9g", healthRating: 5, recommendation: "Sweet beverage. Opt for fresh fruit toppings." },
  { id: 196, name: "Hot Chocolate", category: "Beverages", calories: 190, protein: "6g", carbs: "28g", fats: "6g", healthRating: 5, recommendation: "Sweet comfort drink. Control sugar toppings." },
  { id: 197, name: "Fruit Smoothie", category: "Beverages", calories: 180, protein: "3g", carbs: "42g", fats: "1.5g", healthRating: 8, recommendation: "Good nutrient mix, but high sugar. Include greens." },
  { id: 198, name: "Kombucha", category: "Beverages", calories: 30, protein: "0g", carbs: "7g", fats: "0g", healthRating: 9, recommendation: "Fermented tea rich in probiotics. Great soda swap." },
  { id: 199, name: "Iced Tea", category: "Beverages", calories: 90, protein: "0g", carbs: "23g", fats: "0g", healthRating: 6, recommendation: "Sweetened tea. Opt for unsweetened lemon iced tea." },
  { id: 200, name: "Cold Coffee", category: "Beverages", calories: 180, protein: "5g", carbs: "24g", fats: "7g", healthRating: 6, recommendation: "Contains heavy milk and sugars. Limit frequency." },
  { id: 201, name: "Tomato Juice", category: "Beverages", calories: 17, protein: "0.8g", carbs: "3.5g", fats: "0.1g", healthRating: 9, recommendation: "High lycopene drink. Low calorie and filling." },
  { id: 202, name: "Cranberry Juice", category: "Beverages", calories: 46, protein: "0.4g", carbs: "12.2g", fats: "0.1g", healthRating: 8, recommendation: "Good for urinary tract. Buy unsweetened version." },
  { id: 203, name: "Water", category: "Beverages", calories: 0, protein: "0g", carbs: "0g", fats: "0g", healthRating: 10, recommendation: "Ultimate life fuel. Essential for all body functions." },
  { id: 204, name: "Ginger Ale", category: "Beverages", calories: 80, protein: "0g", carbs: "20g", fats: "0g", healthRating: 5, recommendation: "Carbonated ginger soda. Moderate sugar load." },
  { id: 205, name: "Mocktail", category: "Beverages", calories: 160, protein: "0.5g", carbs: "40g", fats: "0.1g", healthRating: 5, recommendation: "Syrup-heavy punch. Choose drinks based on fresh citrus." },
  { id: 206, name: "Chamomile Tea", category: "Beverages", calories: 1, protein: "0g", carbs: "0.2g", fats: "0g", healthRating: 10, recommendation: "Excellent before bed. Helps calm nerves and improve sleep." },
  { id: 207, name: "Herbal Tea", category: "Beverages", calories: 2, protein: "0.1g", carbs: "0.2g", fats: "0g", healthRating: 10, recommendation: "Caffeine-free extraction of healing herbs." },
  { id: 208, name: "Whey Protein Shake", category: "Beverages", calories: 140, protein: "25g", carbs: "3g", fats: "2g", healthRating: 10, recommendation: "Post-workout essential. Promotes quick muscle synthesis." },
  { id: 209, name: "Aloe Vera Juice", category: "Beverages", calories: 15, protein: "0.1g", carbs: "3.7g", fats: "0.1g", healthRating: 9, recommendation: "Highly anti-inflammatory. Clears skin and aids gut track." },
  { id: 210, name: "Ginger Tea", category: "Beverages", calories: 5, protein: "0.2g", carbs: "1.2g", fats: "0.1g", healthRating: 10, recommendation: "Excellent cold and flu remedy. Relieves congestion." },

  // Breakfast Foods
  { id: 211, name: "Oats", category: "Breakfast Foods", calories: 389, protein: "16.9g", carbs: "66.3g", fats: "6.9g", healthRating: 10, recommendation: "Packed with beta-glucan fiber. Reduces cholesterol levels." },
  { id: 212, name: "Eggs", category: "Breakfast Foods", calories: 155, protein: "12.6g", carbs: "1.1g", fats: "10.6g", healthRating: 9, recommendation: "Gold standard protein. Contains choline for brain health." },
  { id: 213, name: "Cornflakes", category: "Breakfast Foods", calories: 357, protein: "7g", carbs: "84g", fats: "0.4g", healthRating: 6, recommendation: "Processed cereal. Fast digesting. Choose oatmeal instead." },
  { id: 214, name: "Muesli", category: "Breakfast Foods", calories: 380, protein: "10g", carbs: "64g", fats: "7g", healthRating: 8, recommendation: "Contains nuts and seeds. Check for added sugars." },
  { id: 215, name: "Eggs Boiled", category: "Breakfast Foods", calories: 78, protein: "6.3g", carbs: "0.6g", fats: "5.3g", healthRating: 10, recommendation: "Perfect protein portion. Quick and convenient." },
  { id: 216, name: "Eggs Scrambled", category: "Breakfast Foods", calories: 100, protein: "6.3g", carbs: "0.8g", fats: "7.5g", healthRating: 9, recommendation: "Protein rich choice. Limit cooking oil/butter." },
  { id: 217, name: "Omelette", category: "Breakfast Foods", calories: 120, protein: "10g", carbs: "1g", fats: "9g", healthRating: 9, recommendation: "Protein-packed. Whip in spinach and mushrooms." },
  { id: 218, name: "Wheat Bread Toast", category: "Breakfast Foods", calories: 80, protein: "3g", carbs: "15g", fats: "1g", healthRating: 8, recommendation: "Fiber-rich carbohydrate. Limit heavy butter." },
  { id: 219, name: "White Bread Toast", category: "Breakfast Foods", calories: 90, protein: "2.5g", carbs: "18g", fats: "1g", healthRating: 5, recommendation: "Refined flour bread. Swapping with whole wheat is better." },
  { id: 220, name: "French Toast", category: "Breakfast Foods", calories: 220, protein: "6g", carbs: "28g", fats: "9g", healthRating: 6, recommendation: "Egg-dipped bread. Limit syrup to keep sugars low." },
  { id: 221, name: "Pancakes", category: "Breakfast Foods", calories: 227, protein: "6g", carbs: "28g", fats: "10g", healthRating: 5, recommendation: "Control pancake syrup. Serve with fresh fruit toppings." },
  { id: 222, name: "Chia Seed Pudding", category: "Breakfast Foods", calories: 150, protein: "4g", carbs: "18g", fats: "8g", healthRating: 10, recommendation: "Rich in omega-3 and soluble fibers. Outstanding breakfast." },
  { id: 223, name: "Smoothie Bowl", category: "Breakfast Foods", calories: 250, protein: "6g", carbs: "48g", fats: "5g", healthRating: 8, recommendation: "Nutrient dense. Top with chia seeds, almonds, berries." },
  { id: 224, name: "Fruits Bowl", category: "Breakfast Foods", calories: 120, protein: "2g", carbs: "28g", fats: "0.5g", healthRating: 10, recommendation: "Excellent morning detox breakfast. Fresh and vitalizing." },
  { id: 225, name: "Sabudana Khichdi", category: "Breakfast Foods", calories: 320, protein: "2g", carbs: "62g", fats: "8g", healthRating: 6, recommendation: "High starch food. Good for fasting days, low protein." },
  { id: 226, name: "Vermicelli Upma", category: "Breakfast Foods", calories: 230, protein: "5g", carbs: "46g", fats: "4g", healthRating: 7, recommendation: "Add lots of chopped vegetables to improve fiber ratio." },
  { id: 227, name: "Masala Oats", category: "Breakfast Foods", calories: 150, protein: "5g", carbs: "24g", fats: "3g", healthRating: 9, recommendation: "Savory oat breakfast. Hearty and rich in fiber." },
  { id: 228, name: "Rava Dosa", category: "Breakfast Foods", calories: 280, protein: "5g", carbs: "44g", fats: "9g", healthRating: 7, recommendation: "Crispy semolina crepe. Portion control." },
  { id: 229, name: "Appam", category: "Breakfast Foods", calories: 120, protein: "2g", carbs: "24g", fats: "1.5g", healthRating: 8, recommendation: "Light fermented rice pancake. Low fat breakfast." },
  { id: 230, name: "Puttu", category: "Breakfast Foods", calories: 250, protein: "5g", carbs: "48g", fats: "4g", healthRating: 7, recommendation: "Steamed rice-coconut cylinder. Serve with kadala curry." },
  { id: 231, name: "Aloo Paratha", category: "Breakfast Foods", calories: 290, protein: "6g", carbs: "48g", fats: "8g", healthRating: 6, recommendation: "Potato stuffed flatbread. Limit ghee/butter." },
  { id: 232, name: "Paneer Paratha", category: "Breakfast Foods", calories: 320, protein: "12g", carbs: "40g", fats: "12g", healthRating: 8, recommendation: "Good protein flatbread. Ideal for active individuals." },
  { id: 233, name: "Gobi Paratha", category: "Breakfast Foods", calories: 240, protein: "5g", carbs: "38g", fats: "7g", healthRating: 7, recommendation: "Cauliflower flatbread. Healthy everyday breakfast." },
  { id: 234, name: "Methi Paratha", category: "Breakfast Foods", calories: 220, protein: "5.5g", carbs: "36g", fats: "6g", healthRating: 8, recommendation: "Fenugreek flatbread. High fiber and aids blood sugar control." },
  { id: 235, name: "Granola Bar", category: "Breakfast Foods", calories: 180, protein: "4g", carbs: "24g", fats: "7g", healthRating: 7, recommendation: "Convenient snack. Watch out for brown sugar binders." },
  { id: 236, name: "Avocado Toast", category: "Breakfast Foods", calories: 280, protein: "6g", carbs: "24g", fats: "16g", healthRating: 9, recommendation: "Healthy fats and complex carbs. Highly satisfying." },
  { id: 237, name: "Boiled Chickpeas", category: "Breakfast Foods", calories: 164, protein: "9g", carbs: "27g", fats: "2.6g", healthRating: 10, recommendation: "Excellent vegetarian protein. High fiber keeps you full." },
  { id: 238, name: "Idli Sambar", category: "Breakfast Foods", calories: 190, protein: "7g", carbs: "38g", fats: "1.5g", healthRating: 10, recommendation: "Fermented, steamed, virtually fat free. Top tier healthy meal." },
  { id: 239, name: "Dosa Plain", category: "Breakfast Foods", calories: 120, protein: "3g", carbs: "22g", fats: "3g", healthRating: 9, recommendation: "Light fermented crepe. Cook with minimal oil." },
  { id: 240, name: "Poha Veg", category: "Breakfast Foods", calories: 220, protein: "4g", carbs: "42g", fats: "4g", healthRating: 9, recommendation: "Light, digestible flattened rice snack. Load with veggies." },

  // Protein Sources
  { id: 241, name: "Chicken Breast", category: "Protein Sources", calories: 165, protein: "31g", carbs: "0g", fats: "3.6g", healthRating: 10, recommendation: "Ultimate lean protein. Excellent for fat loss and muscle building." },
  { id: 242, name: "Fish", category: "Protein Sources", calories: 206, protein: "22g", carbs: "0g", fats: "12g", healthRating: 9, recommendation: "Rich in omega-3 fatty acids and highly digestible protein." },
  { id: 243, name: "Tofu", category: "Protein Sources", calories: 76, protein: "8g", carbs: "1.9g", fats: "4.8g", healthRating: 9, recommendation: "Soy protein source. Low calorie, rich in calcium and iron." },
  { id: 244, name: "Soybean", category: "Protein Sources", calories: 173, protein: "16.6g", carbs: "9.9g", fats: "9g", healthRating: 9, recommendation: "High protein legume. Contains complete amino acids profile." },
  { id: 245, name: "Salmon", category: "Protein Sources", calories: 206, protein: "22g", carbs: "0g", fats: "12g", healthRating: 10, recommendation: "Incredible source of DHA/EPA omega-3 fats and protein." },
  { id: 246, name: "Tuna", category: "Protein Sources", calories: 132, protein: "28g", carbs: "0g", fats: "1g", healthRating: 9, recommendation: "Extremely lean fish protein. Choose canned in water." },
  { id: 247, name: "Chickpeas", category: "Protein Sources", calories: 164, protein: "9g", carbs: "27g", fats: "2.6g", healthRating: 9, recommendation: "Excellent plant protein and source of folate." },
  { id: 248, name: "Lentils", category: "Protein Sources", calories: 116, protein: "9g", carbs: "20g", fats: "0.4g", healthRating: 10, recommendation: "Core vegetarian protein. High in fiber and iron." },
  { id: 249, name: "Whey Protein", category: "Protein Sources", calories: 120, protein: "24g", carbs: "2g", fats: "1.5g", healthRating: 9, recommendation: "Highly bioavailable milk protein isolate. Speeds recovery." },
  { id: 250, name: "Tempeh", category: "Protein Sources", calories: 193, protein: "19g", carbs: "9g", fats: "11g", healthRating: 9, recommendation: "Fermented soy product. Probiotic and protein powerhouse." },
  { id: 251, name: "Turkey Breast", category: "Protein Sources", calories: 135, protein: "30g", carbs: "0.1g", fats: "1g", healthRating: 9, recommendation: "Super lean poultry protein. Excellent macro ratios." },
  { id: 252, name: "Beef Sirloin", category: "Protein Sources", calories: 250, protein: "26g", carbs: "0g", fats: "15g", healthRating: 7, recommendation: "Rich in iron and B12. Consume in moderation." },
  { id: 253, name: "Pork Chop", category: "Protein Sources", calories: 230, protein: "24g", carbs: "0g", fats: "14g", healthRating: 7, recommendation: "Trim visible fat to optimize lean protein intake." },
  { id: 254, name: "Shrimp", category: "Protein Sources", calories: 99, protein: "24g", carbs: "0.2g", fats: "0.3g", healthRating: 9, recommendation: "Low calorie, high protein seafood. Rich in selenium." },
  { id: 255, name: "Mung Beans", category: "Protein Sources", calories: 105, protein: "7g", carbs: "19g", fats: "0.4g", healthRating: 9, recommendation: "Very easy to digest. Great sprouted." },
  { id: 256, name: "Black Beans", category: "Protein Sources", calories: 132, protein: "9g", carbs: "23g", fats: "0.5g", healthRating: 9, recommendation: "High in fiber and anthocyanin antioxidants." },
  { id: 257, name: "Kidney Beans", category: "Protein Sources", calories: 127, protein: "8.7g", carbs: "22.8g", fats: "0.5g", healthRating: 9, recommendation: "Aids heart health and controls blood glucose spike." },
  { id: 258, name: "Hemp Seeds", category: "Protein Sources", calories: 553, protein: "31.5g", carbs: "8.7g", fats: "48.7g", healthRating: 9, recommendation: "Excellent plant omega-3/6 ratio and complete protein." },
  { id: 259, name: "Almonds", category: "Protein Sources", calories: 579, protein: "21g", carbs: "22g", fats: "49g", healthRating: 9, recommendation: "Healthy fats and moderate protein. Great daily snack." },
  { id: 260, name: "Spirulina", category: "Protein Sources", calories: 290, protein: "57g", carbs: "24g", fats: "8g", healthRating: 9, recommendation: "Blue-green algae superfood. Protein and iron dense." },

  // Dry Fruits
  { id: 261, name: "Almond", category: "Dry Fruits", calories: 579, protein: "21.2g", carbs: "21.6g", fats: "49.9g", healthRating: 9, recommendation: "Excellent brain food. Soaking overnight improves digestion." },
  { id: 262, name: "Cashew", category: "Dry Fruits", calories: 553, protein: "18.2g", carbs: "30.2g", fats: "43.8g", healthRating: 8, recommendation: "Rich in magnesium and iron. Do not consume heavily fried/salted." },
  { id: 263, name: "Walnut", category: "Dry Fruits", calories: 654, protein: "15.2g", carbs: "13.7g", fats: "65.2g", healthRating: 10, recommendation: "Highest dry fruit source of omega-3 alpha-linolenic acid (ALA)." },
  { id: 264, name: "Pistachio", category: "Dry Fruits", calories: 562, protein: "20.2g", carbs: "27.5g", fats: "45.3g", healthRating: 9, recommendation: "Lower calorie nut. Good for eye health (lutein)." },
  { id: 265, name: "Raisins", category: "Dry Fruits", calories: 299, protein: "3g", carbs: "79g", fats: "0.5g", healthRating: 8, recommendation: "Good source of iron and potassium. Natural sugar spike." },
  { id: 266, name: "Dates", category: "Dry Fruits", calories: 277, protein: "1.8g", carbs: "75g", fats: "0.2g", healthRating: 9, recommendation: "Excellent natural sweetener. High in fiber and iron." },
  { id: 267, name: "Dried Figs", category: "Dry Fruits", calories: 249, protein: "3.3g", carbs: "63.9g", fats: "0.9g", healthRating: 8, recommendation: "Very high calcium content for bone strength." },
  { id: 268, name: "Dried Apricots", category: "Dry Fruits", calories: 241, protein: "3.4g", carbs: "62.6g", fats: "0.5g", healthRating: 8, recommendation: "Excellent source of vitamin A (retinol) for skin health." },
  { id: 269, name: "Prunes", category: "Dry Fruits", calories: 240, protein: "2.2g", carbs: "63.8g", fats: "0.4g", healthRating: 9, recommendation: "Famous for relieving constipation. High fiber." },
  { id: 270, name: "Cranberries", category: "Dry Fruits", calories: 308, protein: "0.1g", carbs: "82.8g", fats: "1.4g", healthRating: 7, recommendation: "Antioxidants for urinary tract health. Buy low-sugar options." },
  { id: 271, name: "Chia Seeds", category: "Dry Fruits", calories: 486, protein: "16.5g", carbs: "42.1g", fats: "30.7g", healthRating: 10, recommendation: "Absorbs water and forms gel. Excellent for bowel motility." },
  { id: 272, name: "Flax Seeds", category: "Dry Fruits", calories: 534, protein: "18.3g", carbs: "28.9g", fats: "42.2g", healthRating: 10, recommendation: "Must grind to digest. Incredible source of plant lignans." },
  { id: 273, name: "Pumpkin Seeds", category: "Dry Fruits", calories: 559, protein: "30.2g", carbs: "10.7g", fats: "49.1g", healthRating: 10, recommendation: "Rich in zinc. Excellent support for prostate and hormone health." },
  { id: 274, name: "Sunflower Seeds", category: "Dry Fruits", calories: 584, protein: "20.8g", carbs: "20g", fats: "51.5g", healthRating: 9, recommendation: "Rich source of vitamin E, an essential fat-soluble antioxidant." },
  { id: 275, name: "Sesame Seeds", category: "Dry Fruits", calories: 573, protein: "17.7g", carbs: "23.4g", fats: "49.7g", healthRating: 9, recommendation: "Very high calcium and copper content. Good for joints." },
  { id: 276, name: "Melon Seeds", category: "Dry Fruits", calories: 557, protein: "29g", carbs: "12g", fats: "47g", healthRating: 8, recommendation: "Popular in Indian gravies. Good zinc/magnesium source." },
  { id: 277, name: "Hazelnuts", category: "Dry Fruits", calories: 628, protein: "15g", carbs: "16.7g", fats: "60.8g", healthRating: 9, recommendation: "Rich in folate and healthy fats. Promotes heart wellness." },
  { id: 278, name: "Pecans", category: "Dry Fruits", calories: 691, protein: "9.2g", carbs: "13.9g", fats: "72g", healthRating: 8, recommendation: "Calorie dense nut. Good zinc, portion control." },
  { id: 279, name: "Macadamia Nuts", category: "Dry Fruits", calories: 718, protein: "7.9g", carbs: "13.8g", fats: "75.8g", healthRating: 7, recommendation: "Highly buttery and rich, but very calorie dense." },
  { id: 280, name: "Brazil Nuts", category: "Dry Fruits", calories: 656, protein: "14.3g", carbs: "12.3g", fats: "66.4g", healthRating: 9, recommendation: "Ultimate dietary source of selenium. Eat only 2-3 per day." },

  // Street Food
  { id: 281, name: "Samosa Chaat", category: "Street Food", calories: 340, protein: "6g", carbs: "48g", fats: "15g", healthRating: 4, recommendation: "Crispy samosa with yogurt/spices. High calories and fats." },
  { id: 282, name: "Pav Bhaji", category: "Street Food", calories: 450, protein: "9g", carbs: "62g", fats: "18g", healthRating: 5, recommendation: "Veggies are healthy, but pav is refined bread. Limit butter." },
  { id: 283, name: "Vada Pav", category: "Street Food", calories: 300, protein: "6g", carbs: "44g", fats: "11g", healthRating: 4, recommendation: "Fried potato patty in bread bun. Fast food carb heavy." },
  { id: 284, name: "Veg Momos", category: "Street Food", calories: 150, protein: "4g", carbs: "28g", fats: "2g", healthRating: 6, recommendation: "Steamed dumplings. Limit heavy red chili sauce." },
  { id: 285, name: "Chicken Momos", category: "Street Food", calories: 190, protein: "12g", carbs: "25g", fats: "4g", healthRating: 7, recommendation: "Steamed chicken dumplings. Good protein content." },
  { id: 286, name: "Spring Roll", category: "Street Food", calories: 180, protein: "3.5g", carbs: "24g", fats: "8g", healthRating: 4, recommendation: "Deep-fried veggie roll. High trans fats." },
  { id: 287, name: "Chowmein", category: "Street Food", calories: 320, protein: "7g", carbs: "50g", fats: "11g", healthRating: 5, recommendation: "Very high sodium and oil content. Limit street intake." },
  { id: 288, name: "Veg Manchurian", category: "Street Food", calories: 280, protein: "4g", carbs: "36g", fats: "14g", healthRating: 4, recommendation: "Deep-fried vegetable balls in sodium-rich gravy." },
  { id: 289, name: "Chole Kulche", category: "Street Food", calories: 450, protein: "12g", carbs: "70g", fats: "10g", healthRating: 5, recommendation: "Refined flour kulcha is calorie dense. Chickpeas are good." },
  { id: 290, name: "Aloo Tikki Chaat", category: "Street Food", calories: 290, protein: "5g", carbs: "42g", fats: "12g", healthRating: 4, recommendation: "Fried potato patties with curd and sweet chutney." },
  { id: 291, name: "Dahi Puri", category: "Street Food", calories: 340, protein: "6g", carbs: "48g", fats: "15g", healthRating: 5, recommendation: "Topped with yogurt, sev, chutneys. High in refined carbs." },
  { id: 292, name: "Sev Puri", category: "Street Food", calories: 310, protein: "5g", carbs: "42g", fats: "14g", healthRating: 5, recommendation: "Crunchy flat puris with potato and dry sev toppings." },
  { id: 293, name: "Kachori Chaat", category: "Street Food", calories: 420, protein: "7g", carbs: "52g", fats: "22g", healthRating: 3, recommendation: "Deep fried hard flour shells. Heavy and caloric." },
  { id: 294, name: "Egg Roll", category: "Street Food", calories: 350, protein: "12g", carbs: "38g", fats: "16g", healthRating: 5, recommendation: "Wrap cooked in oil. High protein, moderate calorie load." },
  { id: 295, name: "Chicken Roll", category: "Street Food", calories: 380, protein: "20g", carbs: "40g", fats: "15g", healthRating: 5, recommendation: "Flour wrap filled with spiced chicken. High protein." },
  { id: 296, name: "Paneer Roll", category: "Street Food", calories: 360, protein: "14g", carbs: "40g", fats: "16g", healthRating: 5, recommendation: "High vegetarian protein, but wrap flour and oil are heavy." },
  { id: 297, name: "Frankie Veg", category: "Street Food", calories: 290, protein: "6g", carbs: "45g", fats: "10g", healthRating: 5, recommendation: "Indian street wrap. Control mayo or cheese toppings." },
  { id: 298, name: "Jalebi", category: "Street Food", calories: 150, protein: "1g", carbs: "32g", fats: "3g", healthRating: 2, recommendation: "Deep-fried batter soaked in sugar syrup. Eat rarely." },
  { id: 299, name: "Rabri", category: "Street Food", calories: 400, protein: "10g", carbs: "44g", fats: "20g", healthRating: 4, recommendation: "Thickened sweet milk dessert. Very high sugar content." },
  { id: 300, name: "Kulfi", category: "Street Food", calories: 320, protein: "8g", carbs: "36g", fats: "16g", healthRating: 5, recommendation: "Indian milk ice cream. Caloric but has calcium value." },

  // Healthy Snacks
  { id: 301, name: "Roasted Makhana", category: "Healthy Snacks", calories: 100, protein: "2.5g", carbs: "20g", fats: "1.5g", healthRating: 10, recommendation: "Fox nuts. Low-calorie, gluten-free popped snack. Superb choice." },
  { id: 302, name: "Popcorn", category: "Healthy Snacks", calories: 110, protein: "3g", carbs: "22g", fats: "1.2g", healthRating: 9, recommendation: "Air-popped. Excellent low-calorie volume whole grain snack." },
  { id: 303, name: "Mixed Seeds", category: "Healthy Snacks", calories: 140, protein: "5g", carbs: "6g", fats: "12g", healthRating: 10, recommendation: "Chia, pumpkin, sunflower mix. Rich in zinc and magnesium." },
  { id: 304, name: "Roasted Almonds", category: "Healthy Snacks", calories: 160, protein: "6g", carbs: "6g", fats: "14g", healthRating: 10, recommendation: "Unsalted roasted almonds. High vitamin E and fiber." },
  { id: 305, name: "Hummus with Carrots", category: "Healthy Snacks", calories: 150, protein: "5g", carbs: "18g", fats: "7g", healthRating: 10, recommendation: "High fiber and clean plant-based fats. Perfect mid-day bridge." },
  { id: 306, name: "Roasted Chana", category: "Healthy Snacks", calories: 120, protein: "7g", carbs: "18g", fats: "2g", healthRating: 10, recommendation: "Roasted yellow chickpeas. High in protein, low glycemic." },
  { id: 307, name: "Oatmeal", category: "Healthy Snacks", calories: 150, protein: "5g", carbs: "27g", fats: "2.5g", healthRating: 10, recommendation: "Promotes fullness due to beta-glucan. Great afternoon snack." },
  { id: 308, name: "Cucumber Slices", category: "Healthy Snacks", calories: 15, protein: "0.7g", carbs: "3.6g", fats: "0.1g", healthRating: 10, recommendation: "Perfect near-zero calorie hydrating crunchy snack." },
  { id: 309, name: "Apple with Peanut Butter", category: "Healthy Snacks", calories: 200, protein: "4.5g", carbs: "22g", fats: "12g", healthRating: 9, recommendation: "Satisfying snack blending protein, fiber, and healthy fats." },
  { id: 310, name: "Sprouted Salad", category: "Healthy Snacks", calories: 120, protein: "8g", carbs: "20g", fats: "1g", healthRating: 10, recommendation: "Mung and chana sprouts. Massive digestive enzymes and vitamins." }
];
